### ISSUE TITLE
combat tracker

### ISSUE THREAD

**Issue by Level8Broccoli** [Level8Broccoli/deadlands.oliverbucher.com#19]
- [x] save and sort cards automatically
- [ ] show who's turn it is
- [ ] list current effects (shaken if true and #26)

**Comment by Level8Broccoli** [comment]
- [ ] add/edit manually
